# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest: 
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
#    routing_loader: true
#    view:
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
#    format_listener:
#        rules:
#            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
    routing_loader:
        include_format: false
    view:
        view_response_listener: true
    format_listener:
        rules:
            - { path: '^/api/doc.json', priorities: ['html'], fallback_format: 'html', prefer_extension: false }
            - { path: '^/api/doc', priorities: ['html'], fallback_format: 'html', prefer_extension: false }
            - { path: '^/api/', priorities: ['json'], fallback_format: 'json', prefer_extension: false }
            - { path: '^/pph', priorities: ['html'], fallback_format: 'html', prefer_extension: false }
            - { path: '^/adresse', priorities: ['html'], fallback_format: 'html', prefer_extension: false }
    body_listener:
        enabled: true
        array_normalizer: fos_rest.normalizer.camel_keys