framework:
    secret: '%env(APP_SECRET)%'
    default_locale: fr
    validation: { enable_annotations: true }
    csrf_protection: ~
    #http_method_override: true

    # uncomment this entire section to enable sessions
    session:
        handler_id: ~

    #esi: ~
    #fragments: ~
    php_errors:
        log: true
    templating:
        engines: ['twig']
sensio_framework_extra:
    request:
        converters: true
        auto_convert: false